spring.application.name=backend

# Run SQL init scripts for non-embedded DBs like MySQL
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

price.api.base.url=https://c4rm9elh30.execute-api.us-east-1.amazonaws.com/default

finnhub.api.base.url=https://finnhub.io/api/v1
finnhub.api.key=d9olq1hr01qmf0tb776gd9olq1hr01qmf0tb7770


gemini.api.base.url=https://generativelanguage.googleapis.com
gemini.model=gemini-3.0-flash
gemini.api.key=AQ.Ab8RN6JgvADRp_ARlIG1O1EkUxBe0Tn_DMXADp3VHU9gNXBIOg

