spring.application.name=backend

# Run SQL init scripts for non-embedded DBs like MySQL
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

yahoo.base.url=https://query1.finance.yahoo.com